//
// Created by RodrigoSalad on 13/03/2021.
//

#ifndef CUSTOMBREAKER_DEBUG_CONFIG_H
#define CUSTOMBREAKER_DEBUG_CONFIG_H

//#define ENABLE_DEBUG_ARGS_DICT
//#define ENABLE_DEBUG_FILE_LOAD_BLOCK
//#define ENABLE_DEBUG_FILE_LOAD_PADDLE
//#define ENABLE_DEBUG_FILE_LOAD_BALL
//#define ENABLE_DEBUG_WINDOW

#endif //CUSTOMBREAKER_DEBUG_CONFIG_H
